//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking.Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomImage
    {
        public int Id { get; set; }
        public Nullable<int> RoomInBuilding { get; set; }
        public string Image { get; set; }
    }
}
